# Generated by Django 5.1.3 on 2024-11-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('release_date', models.CharField(max_length=10)),
                ('lte_exists', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
    ]
